-- LASD Radio Code Reference
-- Source: LASD Radio Broadcasting Essential Guide
-- Used by SCC auto-dispatch for proper spoken phrasing.

LASD_CODES = {
    -- Call / situation codes (spoken name used in TTS phrases)
    ["187"]     = { spoken = "One Eight Seven",             desc = "Murder" },
    ["207"]     = { spoken = "Two Oh Seven",                desc = "Kidnapping" },
    ["211"]     = { spoken = "Two Eleven",                  desc = "Robbery" },
    ["211S"]    = { spoken = "Two Eleven Silent",           desc = "Robbery Alarm - Silent" },
    ["215"]     = { spoken = "Two Fifteen",                 desc = "Carjacking" },
    ["242"]     = { spoken = "Two Forty Two",               desc = "Battery" },
    ["245"]     = { spoken = "Two Forty Five",              desc = "Assault with a Deadly Weapon" },
    ["246"]     = { spoken = "Two Forty Six",               desc = "Shooting at an Inhabited Dwelling" },
    ["261"]     = { spoken = "Two Sixty One",               desc = "Rape" },
    ["273A"]    = { spoken = "Two Seventy Three Adam",      desc = "Child Abuse" },
    ["273.5"]   = { spoken = "Two Seventy Three point Five",desc = "Felony Spousal Assault" },
    ["288"]     = { spoken = "Two Eighty Eight",            desc = "Sex Crimes Against Children" },
    ["314"]     = { spoken = "Three Fourteen",              desc = "Indecent Exposure" },
    ["330"]     = { spoken = "Three Thirty",                desc = "Gambling" },
    ["368"]     = { spoken = "Three Sixty Eight",           desc = "Elderly Abuse" },
    ["374B"]    = { spoken = "Three Seventy Four Boy",      desc = "Illegal Dumping" },
    ["390"]     = { spoken = "Three Ninety",                desc = "Drunk" },
    ["390P"]    = { spoken = "Three Ninety Possible",       desc = "Possible Use of PCP" },
    ["415"]     = { spoken = "Four Fifteen",                desc = "Disturbance" },
    ["415B"]    = { spoken = "Four Fifteen Boy",            desc = "Disturbance - Business" },
    ["415D"]    = { spoken = "Four Fifteen David",          desc = "Disturbance - Drunk" },
    ["415E"]    = { spoken = "Four Fifteen Edward",         desc = "Disturbance - Music or Party" },
    ["415F"]    = { spoken = "Four Fifteen Frank",          desc = "Disturbance - Family" },
    ["415FT"]   = { spoken = "Four Fifteen Fight",          desc = "Disturbance - Fight" },
    ["415G"]    = { spoken = "Four Fifteen George",         desc = "Disturbance - Gang Activity" },
    ["415J"]    = { spoken = "Four Fifteen John",           desc = "Disturbance - Juveniles" },
    ["415LT"]   = { spoken = "Four Fifteen Landlord Tenant",desc = "Disturbance - Landlord/Tenant" },
    ["415N"]    = { spoken = "Four Fifteen Nora",           desc = "Disturbance - Neighbors" },
    ["417"]     = { spoken = "Four Seventeen",              desc = "Person with a Gun" },
    ["417A"]    = { spoken = "Four Seventeen Adam",         desc = "Person with a Knife" },
    ["417B"]    = { spoken = "Four Seventeen Boy",          desc = "Barricaded Suspect" },
    ["417BH"]   = { spoken = "Four Seventeen Boy Henry",    desc = "Barricaded Suspect - Hostage Situation" },
    ["417S"]    = { spoken = "Four Seventeen Sam",          desc = "Shots Fired" },
    ["422"]     = { spoken = "Four Twenty Two",             desc = "Terrorist Threats" },
    ["451"]     = { spoken = "Four Fifty One",              desc = "Arson" },
    ["459"]     = { spoken = "Four Fifty Nine",             desc = "Burglary" },
    ["459A"]    = { spoken = "Four Fifty Nine Audible",     desc = "Burglary Alarm - Audible" },
    ["459S"]    = { spoken = "Four Fifty Nine Silent",      desc = "Burglary Alarm - Silent" },
    ["470"]     = { spoken = "Four Seventy",                desc = "Forgery" },
    ["480"]     = { spoken = "Four Eighty",                 desc = "Hit and Run - Felony" },
    ["481"]     = { spoken = "Four Eighty One",             desc = "Hit and Run - Misdemeanor" },
    ["483"]     = { spoken = "Four Eighty Three",           desc = "Hit and Run - Parked Vehicle" },
    ["487"]     = { spoken = "Four Eighty Seven",           desc = "Grand Theft" },
    ["488"]     = { spoken = "Four Eighty Eight",           desc = "Petty Theft" },
    ["488B"]    = { spoken = "Four Eighty Eight Boy",       desc = "Petty Theft - Bicycle" },
    ["496"]     = { spoken = "Four Ninety Six",             desc = "Receiving Stolen Property" },
    ["502"]     = { spoken = "Five Oh Two",                 desc = "Drunk Driving" },
    ["503"]     = { spoken = "Five Oh Three",               desc = "Vehicle Theft" },
    ["503A"]    = { spoken = "Five Oh Three Adam",          desc = "Recovered Vehicle" },
    ["504"]     = { spoken = "Five Oh Four",                desc = "Tampering with Vehicle" },
    ["504A"]    = { spoken = "Five Oh Four Adam",           desc = "Vehicle Stripping" },
    ["510"]     = { spoken = "Five Ten",                    desc = "Speeding or Racing" },
    ["537"]     = { spoken = "Five Thirty Seven",           desc = "Defrauding an Innkeeper" },
    ["586"]     = { spoken = "Five Eighty Six",             desc = "Illegal Parking" },
    ["594"]     = { spoken = "Five Ninety Four",            desc = "Vandalism" },
    ["602"]     = { spoken = "Six Oh Two",                  desc = "Trespassing" },
    ["604"]     = { spoken = "Six Oh Four",                 desc = "Throwing Objects" },
    ["646.9"]   = { spoken = "Six Forty Six point Nine",    desc = "Stalking" },
    ["901N"]    = { spoken = "Nine Oh One Nora",            desc = "Ambulance Needed" },
    ["901S"]    = { spoken = "Nine Oh One Sam",             desc = "Person Sick or Injured" },
    ["901T"]    = { spoken = "Nine Oh One Tom",             desc = "Traffic Collision - Ambulance Dispatched" },
    ["902"]     = { spoken = "Nine Oh Two",                 desc = "Person Sick or Injured" },
    ["902A"]    = { spoken = "Nine Oh Two Adam",            desc = "Attempt Suicide" },
    ["902H"]    = { spoken = "Nine Oh Two Henry",           desc = "Enroute to Hospital" },
    ["902N"]    = { spoken = "Nine Oh Two Nora",            desc = "Traffic Collision - No Injuries" },
    ["902R"]    = { spoken = "Nine Oh Two Robert",          desc = "Rescue Responding" },
    ["902T"]    = { spoken = "Nine Oh Two Tom",             desc = "Traffic Collision - Unknown if Injuries" },
    ["903"]     = { spoken = "Nine Oh Three",               desc = "Aircraft Accident" },
    ["904"]     = { spoken = "Nine Oh Four",                desc = "Fire" },
    ["904A"]    = { spoken = "Nine Oh Four Adam",           desc = "Fire - Auto" },
    ["904B"]    = { spoken = "Nine Oh Four Boy",            desc = "Fire - Brush or Grass" },
    ["904I"]    = { spoken = "Nine Oh Four Ida",            desc = "Smoke Investigation" },
    ["904S"]    = { spoken = "Nine Oh Four Sam",            desc = "Fire - Structure" },
    ["904T"]    = { spoken = "Nine Oh Four Tom",            desc = "Fire - Trash" },
    ["909"]     = { spoken = "Nine Oh Nine",                desc = "Traffic Stop" },
    ["909A"]    = { spoken = "Nine Oh Nine Adam",           desc = "Wires Down" },
    ["909C"]    = { spoken = "Nine Oh Nine Charles",        desc = "Child Locked in Vehicle" },
    ["909S"]    = { spoken = "Nine Oh Nine Sam",            desc = "Safety Hazard" },
    ["909T"]    = { spoken = "Nine Oh Nine Tom",            desc = "Traffic Hazard" },
    ["917A"]    = { spoken = "Nine Seventeen Adam",         desc = "Abandoned Vehicle" },
    ["917S"]    = { spoken = "Nine Seventeen Sam",          desc = "Suspicious Vehicle" },
    ["918"]     = { spoken = "Nine Eighteen",               desc = "Insane Person" },
    ["918V"]    = { spoken = "Nine Eighteen Victor",        desc = "Violently Insane Person" },
    ["920"]     = { spoken = "Nine Twenty",                 desc = "Missing Person" },
    ["920C"]    = { spoken = "Nine Twenty Charles",         desc = "Missing Critical" },
    ["925"]     = { spoken = "Nine Twenty Five",            desc = "Person Acting Suspiciously" },
    ["925A"]    = { spoken = "Nine Twenty Five Adam",       desc = "Person Acting Suspiciously in a Vehicle" },
    ["926"]     = { spoken = "Nine Twenty Six",             desc = "Tow Truck Requested" },
    ["927"]     = { spoken = "Nine Twenty Seven",           desc = "Suspicious Circumstances" },
    ["927B"]    = { spoken = "Nine Twenty Seven Boy",       desc = "Suspicious Circs - Open Door or Window" },
    ["927D"]    = { spoken = "Nine Twenty Seven David",     desc = "Suspicious Circs - Possible Dead Body" },
    ["927H"]    = { spoken = "Nine Twenty Seven Henry",     desc = "9-1-1 Hang Up" },
    ["927P"]    = { spoken = "Nine Twenty Seven Paul",      desc = "Suspicious Circs - Panic Alarm" },
    ["927S"]    = { spoken = "Nine Twenty Seven Sam",       desc = "Suspicious Circs - Person Screaming" },
    ["929"]     = { spoken = "Nine Twenty Nine",            desc = "Person Down" },
    ["996"]     = { spoken = "Nine Ninety Six",             desc = "Explosion" },
    ["996T"]    = { spoken = "Nine Ninety Six Tom",         desc = "Bomb Threat" },
    ["997"]     = { spoken = "Nine Ninety Seven",           desc = "Deputy Needs Help - District Cars" },
    ["998"]     = { spoken = "Nine Ninety Eight",           desc = "Deputy Involved in Shooting" },
    ["999"]     = { spoken = "Nine Ninety Nine",            desc = "Deputy Needs Help - All Units" },
    -- TC used internally for traffic collision shorthand
    ["TC"]      = { spoken = "traffic collision",           desc = "Traffic Collision" },
}

-- Helper: get spoken version of a code, or fall back to the raw string
function getSpokenCode(code)
    local entry = LASD_CODES[tostring(code):upper()]
    return entry and entry.spoken or tostring(code)
end

-- Helper: get description of a code
function getCodeDesc(code)
    local entry = LASD_CODES[tostring(code):upper()]
    return entry and entry.desc or tostring(code)
end
