config = {
    enableMoneyHud = true,
    enableFuelHUD = true,
    enableSpeedometerMetric = false,
    enablePostals = true,

    enableAopStatus = true,
    defaultAopStatus = "Eastwood Park",
    changeAopAccess = { "0" },

    enablePriorityStatus = true,
    cooldownAfterPriorityStops = 5,
    cooldownAccess = { "0" },

    electricVehiles = {
        "Imorgon", "Neon", "Raiden", "Cyclone", "Voltic", "Voltic2", "Tezeract",
        "Dilettante", "Dilettante2", "Airtug", "Caddy", "Caddy2", "Caddy3", "Surge",
        "Khamelion", "RC Bandito"
    },

    GiveSheriffEquipment = true,

    streetNames = {
        -- Eastwood Park (Mirror Park)
        ["Mirror Park Blvd"] = "Eastwood Parkway",
        ["West Mirror Drive"] = "Lakeside Drive West",
        ["East Mirror Drive"] = "Lakeside Drive East",
        ["Nikola Ave"] = "Oakcrest Avenue",
        ["Nikola Pl"] = "Oakcrest Court",
        ["Glory Way"] = "Founders Way",
        ["Bridge St"] = "Civic Center Way",
        ["Mirror Place"] = "Eastwood Plaza",
        ["Amarillo Vista"] = "Ridgeview Terrace",
        ["Amarillo Way"] = "Vista Del Oro",
        ["Lesbos Ln"] = "Willow Lane",
        ["Lesbos Lane"] = "Willow Lane",
        ["Tug St"] = "Industrial Way",
        ["Invention Ct"] = "Innovation Loop",
        ["Coolidge Ave"] = "County Line Road",

        -- LA Core Remaps
        ["Eclipse Blvd"] = "Sunset Boulevard",
        ["West Eclipse Blvd"] = "Sunset Boulevard",
        ["Vespucci Blvd"] = "Santa Monica Boulevard",
        ["San Andreas Ave"] = "Wilshire Boulevard",
        ["South Boulevard Del Perro"] = "Olympic Boulevard",
        ["Boulevard Del Perro"] = "Beverly Boulevard",
        ["Strawberry Ave"] = "Central Avenue",
        ["Innocence Blvd"] = "Compton Boulevard",
        ["Great Ocean Hwy"] = "Pacific Coast Highway",
        ["Los Santos Freeway"] = "The 405 Freeway",
        ["Olympic Fwy"] = "The 10 Freeway",
        ["Del Perro Fwy"] = "The 10 Freeway",
        ["La Puerta Fwy"] = "The 110 Freeway",
        ["Palomino Fwy"] = "The 5 Freeway",
        ["Senora Fwy"] = "The 14 Freeway",
        ["Route 68"] = "State Route 126",
        ["Joshua Rd"] = "Bouquet Canyon Road",
        ["Alta St"] = "Figueroa Street",
        ["Alta Pl"] = "Flower Street",
        ["Power St"] = "Grand Avenue",
        ["Low Power St"] = "Olive Street",
        ["Integrity Way"] = "Hope Street",
        ["Swiss St"] = "Temple Street",
        ["Covenant Ave"] = "Spring Street",
        ["Popular St"] = "Main Street",
        ["San Vitus Blvd"] = "Vine Street",
        ["Vitus St"] = "Western Avenue",
        ["Sinner St"] = "Los Angeles Street",
        ["York St"] = "Colorado Boulevard",
        ["Vinewood Blvd"] = "Hollywood Boulevard",
        ["Vinewood Park Dr"] = "Gower Street",
        ["Gentry Lane"] = "Franklin Avenue",
        ["Whispymound Dr"] = "Mulholland Drive",
        ["Mt Vinewood Dr"] = "Nichols Canyon Road",
        ["Laguna Pl"] = "Franklin Avenue",
        ["Spanish Ave"] = "Highland Avenue",
        ["Marathon Ave"] = "Melrose Avenue",
        ["Meteor St"] = "Fairfax Avenue",
        ["Portola Dr"] = "Rodeo Drive",
        ["Rockford Dr"] = "Canon Drive",
        ["South Rockford Dr"] = "Beverly Drive",
        ["North Rockford Dr"] = "Sunset Plaza Drive",
        ["Dorset Dr"] = "Bedford Drive",
        ["Dorset Pl"] = "Bedford Place",
        ["Milton Rd"] = "Benedict Canyon Drive",
        ["Heritage Way"] = "Burton Way",
        ["Greenwich Pkwy"] = "La Cienega Boulevard",
        ["Greenwich Way"] = "Fairfax Avenue",
        ["Greenwich Pl"] = "Crescent Heights Boulevard",
        ["Magellan Ave"] = "Venice Boulevard",
        ["Bay City Ave"] = "Ocean Avenue",
        ["Bay City Incline"] = "California Incline",
        ["Sandcastle Way"] = "Pacific Avenue",
        ["Prosperity St"] = "Arizona Avenue",
        ["Red Desert Ave"] = "San Vicente Boulevard",
        ["Aguja St"] = "Abbot Kinney Boulevard",
        ["Marina Dr"] = "Admiralty Way",
        ["Cat-Claw Ave"] = "Lincoln Boulevard",
        ["Fantastic Pl"] = "Rose Avenue",
        ["Goma St"] = "Brooks Avenue",
        ["Rub St"] = "Ocean Front Walk",
        ["Tackle St"] = "Vista Del Mar",
        ["Roy Lowenstein Blvd"] = "Florence Avenue",
        ["Davis Ave"] = "Long Beach Boulevard",
        ["Carson Ave"] = "Jefferson Boulevard",
        ["Manchester Ave"] = "Manchester Avenue",
        ["Rancho Blvd"] = "Avalon Boulevard",
        ["Jamestown St"] = "Wilmington Avenue",
        ["Macdonald St"] = "Alameda Street",
        ["Brouge Ave"] = "3rd Street",
        ["Carcer Way"] = "4th Street",
        ["Little Bighorn Ave"] = "5th Street",
        ["Orchardville Ave"] = "6th Street",
        ["South Arsenal St"] = "7th Street",
        ["Abattoir Ave"] = "Soto Street",
        ["El Rancho Blvd"] = "Whittier Boulevard",
        ["Signal St"] = "Atlantic Boulevard",
        ["Sustancia Rd"] = "Eastern Avenue",
        ["Dry Dock St"] = "Terminal Island Freeway",
        ["Hanger Way"] = "Ocean Boulevard",
        ["Mutiny Rd"] = "Shoreline Drive",
        ["Terminal Way"] = "Seaside Avenue",
        ["Calafia Rd"] = "Soledad Canyon Road",
        ["Zancudo Rd"] = "San Francisquito Canyon Road",
        ["Banham Canyon Dr"] = "Topanga Canyon Boulevard",
        ["Tongva Dr"] = "Malibu Canyon Road",
        ["Algonquin Blvd"] = "Sierra Highway",
        ["Armadillo Ave"] = "Sierra Highway",
        ["Senora Rd"] = "Sierra Highway",
        ["Senora Way"] = "Soledad Canyon Road",
        ["Cholla Rd"] = "Lancaster Boulevard",
        ["Cholla Springs Ave"] = "Avenue J",
        ["Niland Ave"] = "Avenue K",
        ["Peaceful St"] = "Avenue L",
        ["Smoke Tree Rd"] = "Avenue M",
        ["Tangerine St"] = "Avenue N",
        ["Capital Blvd"] = "Elizabeth Lake Road",
        ["Mt Haan Rd"] = "Angeles Crest Highway",
        ["Perth St"] = "Hope Street",
        ["Crusade Rd"] = "Grand Avenue",
        ["Sam Austin Dr"] = "Stone Canyon Road",
        ["Americano Way"] = "Alta Avenue",
        ["Sinners Passage"] = "St. James Place",
        ["Mountain View Dr"] = "Mountain View Drive",
        ["El Burro Blvd"] = "State Street",
        ["Chupacabra St"] = "Santa Fe Avenue",
        ["Playa Vista"] = "Playa Vista Boulevard",
        ["Marlowe Dr"] = "Marlowe Drive",
        ["Alhambra Dr"] = "Alhambra Drive",
        ["New Empire Way"] = "New Empire Way",
        ["Melanoma St"] = "Sepulveda Boulevard",
        ["Movie Star Way"] = "Universal Studios Boulevard",
        ["Strangeways Dr"] = "Barham Boulevard",
        ["Equality Way"] = "Imperial Highway",
        ["Zancudo Grande Valley"] = "Zancudo Valley",
        ["Elgin Ave"] = "Elgin Avenue",
        ["Cortes St"] = "Bandini Boulevard",
        ["Atlee St"] = "Atlee Street",
        ["Ace Jones Dr"] = "Ace Jones Drive",
        ["Baytree Canyon Rd"] = "Baytree Canyon Road",
        ["Abe Milton Pkwy"] = "Abe Milton Parkway",
        ["Decker St"] = "Gage Avenue",
        ["Mad Wayne Thunder Dr"] = "Mad Wayne Thunder Drive",
        ["Steele Way"] = "Steele Way",
        ["Kortz Dr"] = "Kortz Drive",
        ["North Archer Ave"] = "North Archer Avenue",
        ["Caesars Place"] = "Caesars Place",
        ["Autopia Pkwy"] = "Autopia Parkway",
        ["Calais Ave"] = "Calais Avenue",
        ["Fudge Ln"] = "Fudge Lane",
        ["Hillcrest Ave"] = "Hillcrest Avenue",
        ["Zancudo Ave"] = "Zancudo Avenue",
        ["West Galileo Ave"] = "West Galileo Avenue",
        ["Richman St"] = "Richman Street",
        ["Zancudo Barranca"] = "Zancudo Barranca",
        ["Exceptionalists Way"] = "Aviation Boulevard",
        ["Dunstable Ln"] = "Dunstable Lane",
        ["Hawick Ave"] = "Hawick Avenue",
        ["Dunstable Dr"] = "Dunstable Drive",
        ["Miriam Turner Overpass"] = "Miriam Turner Overpass",
        ["Cox Way"] = "Cox Way",
        ["Goma St"] = "Brooks Avenue",
        ["North Conker Ave"] = "North Conker Avenue",
        ["Panorama Dr"] = "Panorama Drive",
        ["Eastbourne Way"] = "Eastbourne Way",
        ["South Mo Milton Dr"] = "South Mo Milton Drive",
        ["Dutch London St"] = "Sepulveda Boulevard",
        ["Edwood Way"] = "Edwood Way",
        ["Hardy Way"] = "Hardy Way",
        ["Labor Pl"] = "Labor Place",
        ["Tower Way"] = "Tower Way",
        ["Liberty St"] = "Liberty Street",
        ["Meringue Ln"] = "Meringue Lane",
        ["Utopia Gardens"] = "Utopia Gardens",
        ["Cougar Ave"] = "Cougar Avenue",
        ["Ginger St"] = "Ginger Street",
        ["Morningwood Blvd"] = "Morningwood Boulevard",
        ["Lolita Ave"] = "Lolita Avenue",
        ["Chum St"] = "Chum Street",
        ["Imagination Ct"] = "Imagination Court",
        ["Didion Dr"] = "Didion Drive"
    },

    zoneNames = {
        ["Mirror Park"] = "City of Eastwood Park",
        ["Vinewood"] = "Hollywood",
        ["East Vinewood"] = "East Hollywood",
        ["West Vinewood"] = "West Hollywood",
        ["Downtown Vinewood"] = "Hollywood",
        ["Rockford Hills"] = "Beverly Hills",
        ["Richman"] = "Bel Air",
        ["Morningwood"] = "Westwood",
        ["Vespucci"] = "Venice",
        ["Del Perro"] = "Santa Monica",
        ["Chumash"] = "Malibu",
        ["Pacific Bluffs"] = "Pacific Palisades",
        ["Rancho"] = "Watts",
        ["Davis"] = "Compton",
        ["Strawberry"] = "South Los Angeles",
        ["Chamberlain Hills"] = "Baldwin Hills",
        ["La Puerta"] = "Harbor Gateway",
        ["Banning"] = "Wilmington",
        ["Terminal"] = "Port of Los Angeles",
        ["Elysian Island"] = "Terminal Island",
        ["Cypress Flats"] = "Vernon",
        ["Murrieta Heights"] = "Boyle Heights",
        ["La Mesa"] = "Arts District",
        ["Textile City"] = "Fashion District",
        ["Mission Row"] = "Historic Core",
        ["Pillbox Hill"] = "Bunker Hill",
        ["Legion Square"] = "Pershing Square",
        ["Burton"] = "Mid-Wilshire",
        ["Hawick"] = "Melrose",
        ["Alta"] = "Chinatown",
        ["Little Seoul"] = "Koreatown",
        ["Grand Senora Desert"] = "Antelope Valley",
        ["Sandy Shores"] = "Lancaster",
        ["Grapeseed"] = "Palmdale",
        ["Harmony"] = "Quartz Hill",
        ["Paleto Bay"] = "Santa Clarita",
        ["Paleto Forest"] = "Angeles National Forest",
        ["Mount Chiliad"] = "Mount San Antonio",
        ["Great Chaparral"] = "Santa Clarita Valley",
        ["Tongva Hills"] = "Topanga",
        ["Banham Canyon"] = "Pacific Palisades",
        ["Galileo Park"] = "Griffith Park",
        ["Vinewood Hills"] = "Hollywood Hills",
        ["Downtown"] = "Downtown LA"
    }
}

-- NUI HUD layout overrides (per resolution/aspect) via CSS variables.
-- Values must be valid CSS (e.g. "260px", "16vw", "clamp(200px, 17vw, 380px)").
-- For sizing scale, use a number (e.g. 0.9, 1.0, 1.15).
config.hudLayout = {
    enabled = true,

    -- Baseline applied to every screen.
    default = {
        ["--hud-size-scale"] = 1.0,
        ["--hud-left"] = "clamp(200px, 17.5vw, 380px)",
        ["--hud-right"] = "clamp(16px, 2vw, 48px)",
        ["--hud-bottom"] = "clamp(18px, 3.5vh, 48px)"
    },

    -- Optional exact resolution overrides (wins over aspect rules).
    -- Example:
    -- resolutions = {
    --     ["2560x1080"] = { ["--hud-left"] = "clamp(240px, 13vw, 420px)", ["--hud-size-scale"] = 1.0 }
    -- },
    resolutions = {
        ["2560x1440"] = { ["--hud-left"] = "clamp(240px, 20vw, 420px)", ["--hud-size-scale"] = 1.0 },
        ["1920x1440"] = { ["--hud-left"] = "clamp(240px, 21vw, 420px)", ["--hud-size-scale"] = 1.0 }
        
    },

    -- Optional aspect-ratio presets (applied when aspect matches).
    -- These merge on top of `default` (and below exact `resolutions`).
    aspect = {
        ultrawide = {
            min = 2.0, -- 21:9 ~= 2.33
            vars = {
                ["--hud-left"] = "clamp(240px, 13vw, 420px)"
            }
        },
        narrow = {
            max = 1.5, -- 4:3 ~= 1.33
            vars = {
                ["--hud-left"] = "clamp(160px, 20vw, 320px)"
            }
        }
    }
}

config.damageFeed = {
    enabled = true,
    minDamage = 1,
    throttleMs = 250,
    dedupeWindowMs = 500,
    contextWindowMs = 600,
    showHealth = true,
    chatColor = { 255, 150, 150 }
}

config.injuryEffects = {
    enabled = true,
    minImpactDamage = 3,
    maxSeverity = 100,
    decayIntervalMs = 1000,
    decayPerTick = 1.5,
    minHealthRegenMultiplier = 0.2,

    legLimpThreshold = 24,
    legNoSprintThreshold = 58,
    armRecoilThreshold = 20,
    chestShakeThreshold = 32,
    headBlurThreshold = 38,

    locationWeight = {
        ["Head"] = 1.45,
        ["Neck"] = 1.25,
        ["Chest"] = 1.0,
        ["Stomach"] = 1.0,
        ["Upper Back"] = 0.95,
        ["Lower Back"] = 0.95,
        ["Spine"] = 0.95,
        ["Left Arm"] = 1.05,
        ["Right Arm"] = 1.05,
        ["Left Forearm"] = 1.1,
        ["Right Forearm"] = 1.1,
        ["Left Hand"] = 1.1,
        ["Right Hand"] = 1.1,
        ["Left Leg"] = 1.2,
        ["Right Leg"] = 1.2,
        ["Left Foot"] = 1.2,
        ["Right Foot"] = 1.2,
        ["Body"] = 1.0
    },

    categoryMultiplier = {
        firearm = 1.1,
        melee = 0.9,
        vehicle = 1.25,
        fall = 1.0,
        explosion = 1.35,
        fire = 0.8,
        drowning = 0.75,
        unknown = 1.0
    }
}
